name: Upload Package

on:
  push:
    branches:
      - main

jobs:
  upload-package:
    runs-on: ubuntu-latest

    steps:
      - name: Use deploy world action
        uses: hypersonic-laboratories/deploy-world@main
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          world_name: 'we7c5d4'

